AWSTemplateFormatVersion: '2010-09-09'

Description: CloudFormation Template for an S3 Bucket Provisioned via GitHub Approval Workflow

Parameters:

  BucketName:
    Type: String

  AWSRegion:
    Type: String

  VersioningEnabled:
    Type: String
    Default: 'false'
    AllowedValues:
      - 'true'
      - 'false'

  EncryptionType:
    Type: String
    Default: AES256
    AllowedValues:
      - AES256
      - aws:kms

  KmsKeyId:
    Type: String
    Default: ''

Conditions:

  EnableVersioning: !Equals [ !Ref VersioningEnabled, 'true' ]
  UseKMS: !Equals [ !Ref EncryptionType, 'aws:kms' ]
  HasKmsKeyId: !Not [ !Equals [ !Ref KmsKeyId, '' ] ]
  UseProvidedKms: !And [ !Condition UseKMS, !Condition HasKmsKeyId ]

  # Only required for non-us-east-1
  NotUSEast1: !Not [ !Equals [ !Ref AWSRegion, 'us-east-1' ] ]

Resources:

  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

      OwnershipControls:
        Rules:
          - ObjectOwnership: BucketOwnerEnforced

      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        IgnorePublicAcls: true
        BlockPublicPolicy: true
        RestrictPublicBuckets: true

      # Add LocationConstraint only when region != us-east-1
      CreateBucketConfiguration:
        Fn::If:
          - NotUSEast1
          - 
            LocationConstraint: !Ref AWSRegion
          - !Ref AWS::NoValue

      VersioningConfiguration:
        Fn::If:
          - EnableVersioning
          - 
            Status: Enabled
          - !Ref AWS::NoValue

      BucketEncryption:
        Fn::If:
          - UseProvidedKms
          - 
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: aws:kms
                  KMSMasterKeyID: !Ref KmsKeyId
          - 
            ServerSideEncryptionConfiguration:
              - ServerSideEncryptionByDefault:
                  SSEAlgorithm: AES256

Outputs:

  BucketArn:
    Description: ARN of the S3 Bucket
    Value: !GetAtt S3Bucket.Arn